
name: CI Linux Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Test Docker Build
      run: |
        set -x
        docker build -t metacall/nodejs-c-liburing-example .
        docker run -p 28977:28977 --name metacall_test -d metacall/nodejs-c-liburing-example
        sleep 10
        docker ps
        docker logs metacall_test
        curl localhost:28977 || exit 1


# until [ "`docker inspect -f {{.State.Health.Status}} metacall_test`" == "healthy" ]; do
#     sleep 1
# done
